<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <EnableComHosting>true</EnableComHosting>
    <EnableUnmanagedCodeSupport>true</EnableUnmanagedCodeSupport>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <WarningLevel>9999</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <WarningLevel>9999</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Images\ADD_DOCUMENT.png" />
    <None Remove="Images\ANULADO_DOCUMENTO.png" />
    <None Remove="Images\CLOSE_DOCUMENT.png" />
    <None Remove="Images\OPEN_DOCUMENT.png" />
    <None Remove="Reports\Inventario\Report_Inventarios_RollosCortados.rdlc" />
    <None Remove="Reports\Inventario\Report_Inventario_Master.rdlc" />
    <None Remove="Reports\Production\DsProduccion.xsd" />
    <None Remove="Reports\Production\ReporteOC.rdlc" />
    <None Remove="Reports\RptConduceConPrecio.rdlc" />
    <None Remove="Reports\RptOC.rdlc" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Images\ADD_DOCUMENT.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Images\CLOSE_DOCUMENT.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Images\OPEN_DOCUMENT.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Reports\Inventario\Report_Inventarios_RollosCortados.rdlc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Reports\Inventario\Report_Inventario_Master.rdlc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Reports\Production\DsProduccion.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>DsProduccion.Designer.cs</LastGenOutput>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Reports\Production\ReporteOC.rdlc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Reports\RptImportFormat.rdlc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Reports\RptConduceConPrecio.rdlc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Reports\RptOC.rdlc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="ReportViewerCore.WinForms" Version="15.1.33" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Images\ANULADO_DOCUMENTO.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
    <Compile Update="Reports\DsConduce.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DsConduce.xsd</DependentUpon>
    </Compile>
    <Compile Update="Reports\Inventario\DsInventarios.Designer.cs">
      <DependentUpon>DsInventarios.xsd</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Reports\Production\DsProduccion.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DsProduccion.xsd</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Paquetes\TSCLIB.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <None Update="Reports\DsConduce.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>DsConduce.Designer.cs</LastGenOutput>
    </None>
    <None Update="Reports\Inventario\DsInventarios.xsd">
      <SubType>Designer</SubType>
      <LastGenOutput>DsInventarios.Designer.cs</LastGenOutput>
      <Generator>MSDataSetGenerator</Generator>
    </None>
    <None Update="Reports\Picking-List.rdlc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Reports\RptConduceSinPrecio.rdlc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Reports\RptDetalle-Paleta.rdlc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>